SET SQLBLANKLINES ON

CREATE SEQUENCE AMENITY_ID_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;

CREATE SEQUENCE HOTEL_ID_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;

CREATE SEQUENCE OPINION_ID_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;

CREATE SEQUENCE RESERVATION_ID_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;

CREATE SEQUENCE ROOM_ID_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;

CREATE SEQUENCE USER_ID_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;

CREATE TABLE AMENITY_TYPES 
(
  AMENITY_TYPE_CD VARCHAR2(5)
, AMENITY_NAME VARCHAR2(50) NOT NULL 
, CONSTRAINT AMENITY_TYPES_PK PRIMARY KEY 
  (
    AMENITY_TYPE_CD 
  )
  ENABLE 
);

CREATE TABLE HOTELS 
(
  HOTEL_ID NUMBER(6) DEFAULT HOTEL_ID_SEQ.NEXTVAL NOT NULL 
, NAME VARCHAR2(100 CHAR) NOT NULL 
, EMAIL VARCHAR2(50 CHAR) NOT NULL 
, RATING NUMBER(1) NOT NULL 
, PHONE_NUMBER VARCHAR2(16) NOT NULL 
, STREET VARCHAR2(100 CHAR) NOT NULL 
, POSTAL_CODE VARCHAR2(16 CHAR) NOT NULL 
, LOCALITY VARCHAR2(100 CHAR) NOT NULL 
, COUNTRY VARCHAR2(60 CHAR) NOT NULL 
, BUILDING_NUMBER VARCHAR2(6 CHAR) NOT NULL 
, APARTMENT_NUMBER VARCHAR2(6 CHAR) 
);

CREATE TABLE PROPERTIES 
(
  PROPERTY_CD VARCHAR2(5)
, PROPERTY_NAME VARCHAR2(50) NOT NULL 
, DATA_TYPE CHAR(1) NOT NULL 
, OPTIONAL CHAR(1) NOT NULL 
, CONSTRAINT PROPERTIES_PK PRIMARY KEY 
  (
    PROPERTY_CD 
  )
  ENABLE 
);

CREATE TABLE USERS 
(
  USER_ID NUMBER(7) DEFAULT USER_ID_SEQ.NEXTVAL NOT NULL 
, FIRST_NAME VARCHAR2(30) NOT NULL 
, LAST_NAME VARCHAR2(30) NOT NULL 
, EMAIL VARCHAR2(50) NOT NULL 
, PHONE_NUMBER VARCHAR2(16) NOT NULL 
, GENDER CHAR(1) 
, STREET VARCHAR2(100) NOT NULL 
, POSTAL_CODE VARCHAR2(16) NOT NULL 
, LOCALITY VARCHAR2(100) NOT NULL 
, COUNTRY VARCHAR2(60) NOT NULL 
, BUILDING_NUMBER VARCHAR2(6) NOT NULL 
, APARTMENT_NUMBER VARCHAR2(6) 
, CONSTRAINT USERS_PK PRIMARY KEY 
  (
    USER_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX USERS_PK_IDX ON USERS (USER_ID ASC) 
  )
  ENABLE 
);

CREATE TABLE AMENITIES 
(
  AMENITY_ID NUMBER(7) DEFAULT AMENITY_ID_SEQ.NEXTVAL NOT NULL 
, AMENITY_TYPE_CD VARCHAR2(5) NOT NULL 
, HOTEL_ID NUMBER(6) NOT NULL 
, CONSTRAINT AMENITIES_PK PRIMARY KEY 
  (
    AMENITY_ID 
  )
  ENABLE 
);

CREATE TABLE ROOMS 
(
  ROOM_ID NUMBER(7) DEFAULT ROOM_ID_SEQ.NEXTVAL NOT NULL 
, ROOM_NUMBER VARCHAR2(10) NOT NULL 
, BED_QUANTITY NUMBER(2) NOT NULL 
, ROOM_STANDARD VARCHAR2(20) NOT NULL 
, PRICE_PER_NIGHT NUMBER(6, 2) NOT NULL 
, MAX_OCCUPANCY NUMBER(2) NOT NULL 
, HOTEL_ID NUMBER(6) NOT NULL 
, CONSTRAINT ROOMS_PK PRIMARY KEY 
  (
    ROOM_ID 
  )
  ENABLE 
);

CREATE TABLE AMENITY_TYPE_PROPERTIES 
(
  PROPERTY_CD VARCHAR2(5) NOT NULL 
, AMENITY_TYPE_CD VARCHAR2(5) NOT NULL 
, CONSTRAINT AMENITY_TYPE_PROPERTIES_PK PRIMARY KEY 
  (
    PROPERTY_CD 
  , AMENITY_TYPE_CD 
  )
  ENABLE 
);

CREATE TABLE OPINIONS 
(
  OPINION_ID NUMBER(8) DEFAULT OPINION_ID_SEQ.NEXTVAL NOT NULL 
, RATING NUMBER(1) NOT NULL 
, ADDED_DATE DATE NOT NULL 
, OPINION_TEXT VARCHAR2(1000) 
, USER_ID NUMBER(7) NOT NULL 
, HOTEL_ID NUMBER(6) NOT NULL 
, CONSTRAINT OPINIONS_PK PRIMARY KEY 
  (
    OPINION_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OPINIONS_PK_IDX ON OPINIONS (OPINION_ID ASC) 
  )
  ENABLE 
);

CREATE TABLE RESERVATIONS 
(
  RESERVATION_ID NUMBER(7) DEFAULT RESERVATION_ID_SEQ.NEXTVAL NOT NULL 
, USER_ID NUMBER(7) NOT NULL 
, PAYMENT_STATUS VARCHAR2(20) NOT NULL 
, PAYMENT_METHOD VARCHAR2(20) NOT NULL 
, PAYMENT_AMOUNT NUMBER(7, 2) NOT NULL 
, PAYMENT_EXECUTION_TIME DATE 
, CONSTRAINT RESERVATIONS_PK PRIMARY KEY 
  (
    RESERVATION_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX RESERVATIONS_PK_IDX ON RESERVATIONS (RESERVATION_ID ASC) 
  )
  ENABLE 
);

CREATE TABLE PROPERTY_VALUES 
(
  AMENITY_ID NUMBER(7) NOT NULL 
, PROPERTY_CD VARCHAR2(5) NOT NULL 
, AMENITY_TYPE_CD VARCHAR2(5) NOT NULL 
, VALUE VARCHAR2(50) NOT NULL 
);

CREATE TABLE ROOM_RESERVATIONS 
(
  RESERVATION_ID NUMBER(7) NOT NULL 
, ROOM_ID NUMBER(7) NOT NULL 
, START_DATE DATE NOT NULL 
, END_DATE DATE NOT NULL 
, NUMBER_OF_GUESTS NUMBER(2) NOT NULL 
, BREAKFAST_COUNT NUMBER(2) NOT NULL 
, LUNCH_COUNT NUMBER(2) NOT NULL 
, DINNER_COUNT NUMBER(2) NOT NULL 
, CONSTRAINT ROOM_RESERVATIONS_PK PRIMARY KEY 
  (
    ROOM_ID 
  , RESERVATION_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX ROOM_RESERVATIONS_PK_IDX ON ROOM_RESERVATIONS (RESERVATION_ID ASC, ROOM_ID ASC) 
  )
  ENABLE 
);

CREATE INDEX AMENITIES_AMENITY_TYPE_IDX ON AMENITIES (AMENITY_TYPE_CD);

CREATE INDEX AMENITIES_HOTEL_IDX ON AMENITIES (HOTEL_ID);

CREATE INDEX AMENITY_TYPE_PROP_AME_TYP_IDX ON AMENITY_TYPE_PROPERTIES (AMENITY_TYPE_CD);

CREATE INDEX HOTELS_PK_IDX ON HOTELS (HOTEL_ID);

CREATE INDEX OPINIONS_HOTEL_IDX ON OPINIONS (HOTEL_ID);

CREATE INDEX OPINIONS_USER_IDX ON OPINIONS (USER_ID);

CREATE INDEX PROPERTY_VALUES_AT_IDX ON PROPERTY_VALUES (PROPERTY_CD, AMENITY_TYPE_CD);

CREATE UNIQUE INDEX PROPERTY_VALUES_PK ON PROPERTY_VALUES (AMENITY_ID ASC, PROPERTY_CD ASC, AMENITY_TYPE_CD ASC);

CREATE INDEX RESERVATIONS_USER_IDX ON RESERVATIONS (USER_ID);

CREATE INDEX ROOMS_HOTEL_IDX ON ROOMS (HOTEL_ID);

CREATE INDEX ROOM_RESERVATIONS_ROOM_IDX ON ROOM_RESERVATIONS (ROOM_ID);

ALTER TABLE HOTELS
ADD CONSTRAINT HOTELS_PK_IDX PRIMARY KEY 
(
  HOTEL_ID 
)
USING INDEX HOTELS_PK_IDX
ENABLE;

ALTER TABLE PROPERTY_VALUES
ADD CONSTRAINT PROPERTY_VALUES_PK PRIMARY KEY 
(
  AMENITY_ID 
, PROPERTY_CD 
, AMENITY_TYPE_CD 
)
USING INDEX PROPERTY_VALUES_PK
ENABLE;

ALTER TABLE AMENITY_TYPES
ADD CONSTRAINT AMENITY_TYPES_UK1 UNIQUE 
(
  AMENITY_NAME 
)
ENABLE;

ALTER TABLE HOTELS
ADD CONSTRAINT HOTELS_EMAIL_UK UNIQUE 
(
  EMAIL 
)
USING INDEX 
(
    CREATE UNIQUE INDEX HOTELS_EMAIL_IDX ON HOTELS (EMAIL ASC) 
)
 ENABLE;

ALTER TABLE HOTELS
ADD CONSTRAINT HOTELS_NAME_UK UNIQUE 
(
  NAME 
)
USING INDEX 
(
    CREATE UNIQUE INDEX HOTELS_UK1 ON HOTELS (NAME ASC) 
)
 ENABLE;

ALTER TABLE HOTELS
ADD CONSTRAINT HOTELS_PHONE_NUMBER_UK UNIQUE 
(
  PHONE_NUMBER 
)
USING INDEX 
(
    CREATE UNIQUE INDEX HOTELS_PHONE_NUMBER_IDX ON HOTELS (PHONE_NUMBER ASC) 
)
 ENABLE;

ALTER TABLE PROPERTIES
ADD CONSTRAINT PROPERTIES_NAME_UK UNIQUE 
(
  PROPERTY_NAME 
)
USING INDEX 
(
    CREATE UNIQUE INDEX PROPERTIES_UK1 ON PROPERTIES (PROPERTY_NAME ASC) 
)
 ENABLE;

ALTER TABLE ROOMS
ADD CONSTRAINT ROOMS_NUMBER_UK UNIQUE 
(
  ROOM_NUMBER 
)
USING INDEX 
(
    CREATE UNIQUE INDEX ROOMS_UK1 ON ROOMS (ROOM_NUMBER ASC) 
)
 ENABLE;

ALTER TABLE USERS
ADD CONSTRAINT USERS_EMAIL_UK UNIQUE 
(
  EMAIL 
)
USING INDEX 
(
    CREATE UNIQUE INDEX USERS_UK1 ON USERS (EMAIL ASC) 
)
 ENABLE;

ALTER TABLE USERS
ADD CONSTRAINT USERS_PHONE_UK UNIQUE 
(
  PHONE_NUMBER 
)
USING INDEX 
(
    CREATE UNIQUE INDEX USERS_UK2 ON USERS (PHONE_NUMBER ASC) 
)
 ENABLE;

ALTER TABLE AMENITIES
ADD CONSTRAINT AMENITIES_AME_TYP_FK FOREIGN KEY
(
  AMENITY_TYPE_CD 
)
REFERENCES AMENITY_TYPES
(
  AMENITY_TYPE_CD 
)
ENABLE;

ALTER TABLE AMENITIES
ADD CONSTRAINT AMENITIES_HOTEL_FK FOREIGN KEY
(
  HOTEL_ID 
)
REFERENCES HOTELS
(
  HOTEL_ID 
)
ENABLE;

ALTER TABLE AMENITY_TYPE_PROPERTIES
ADD CONSTRAINT AMENITY_TYPE_PROP_AME_TYP_FK FOREIGN KEY
(
  AMENITY_TYPE_CD 
)
REFERENCES AMENITY_TYPES
(
  AMENITY_TYPE_CD 
)
ENABLE;

ALTER TABLE AMENITY_TYPE_PROPERTIES
ADD CONSTRAINT AMENITY_TYPE_PROP_PROP_FK FOREIGN KEY
(
  PROPERTY_CD 
)
REFERENCES PROPERTIES
(
  PROPERTY_CD 
)
ENABLE;

ALTER TABLE OPINIONS
ADD CONSTRAINT OPINIONS_HOTEL_FK FOREIGN KEY
(
  HOTEL_ID 
)
REFERENCES HOTELS
(
  HOTEL_ID 
)
ENABLE;

ALTER TABLE OPINIONS
ADD CONSTRAINT OPINIONS_USER_FK FOREIGN KEY
(
  USER_ID 
)
REFERENCES USERS
(
  USER_ID 
)
ENABLE;

ALTER TABLE PROPERTY_VALUES
ADD CONSTRAINT PROPERTY_VALUES_AMENITY_FK FOREIGN KEY
(
  AMENITY_ID 
)
REFERENCES AMENITIES
(
  AMENITY_ID 
)
ENABLE;

ALTER TABLE PROPERTY_VALUES
ADD CONSTRAINT PROPERTY_VALUES_AME_TYP_FK FOREIGN KEY
(
  PROPERTY_CD 
, AMENITY_TYPE_CD 
)
REFERENCES AMENITY_TYPE_PROPERTIES
(
  PROPERTY_CD 
, AMENITY_TYPE_CD 
)
ENABLE;

ALTER TABLE RESERVATIONS
ADD CONSTRAINT RESERVATIONS_USER_FK FOREIGN KEY
(
  USER_ID 
)
REFERENCES USERS
(
  USER_ID 
)
ENABLE;

ALTER TABLE ROOMS
ADD CONSTRAINT ROOMS_HOTEL_FK FOREIGN KEY
(
  HOTEL_ID 
)
REFERENCES HOTELS
(
  HOTEL_ID 
)
ENABLE;

ALTER TABLE ROOM_RESERVATIONS
ADD CONSTRAINT ROOM_RESERVATIONS_RESERV_FK FOREIGN KEY
(
  RESERVATION_ID 
)
REFERENCES RESERVATIONS
(
  RESERVATION_ID 
)
ENABLE;

ALTER TABLE ROOM_RESERVATIONS
ADD CONSTRAINT ROOM_RESERVATIONS_ROOMS_FK FOREIGN KEY
(
  ROOM_ID 
)
REFERENCES ROOMS
(
  ROOM_ID 
)
ENABLE;

ALTER TABLE HOTELS
ADD CONSTRAINT HOTELS_EMAIL_CHK CHECK 
(REGEXP_LIKE(Email, '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'))
ENABLE;

ALTER TABLE HOTELS
ADD CONSTRAINT HOTELS_RATING_CHK CHECK 
(RATING BETWEEN 0 AND 5)
ENABLE;

ALTER TABLE OPINIONS
ADD CONSTRAINT OPINIONS_RATING_CHK CHECK 
(RATING BETWEEN 0 AND 5)
ENABLE;

ALTER TABLE PROPERTIES
ADD CONSTRAINT PROPERTIES_DATA_TYPE_CHK CHECK 
(DATA_TYPE IN ('T',  'N'))
ENABLE;

ALTER TABLE PROPERTIES
ADD CONSTRAINT PROPERTIES_OPT_CHK CHECK 
(OPTIONAL IN ('Y', 'N'))
ENABLE;

ALTER TABLE RESERVATIONS
ADD CONSTRAINT RESERVATIONS_PAY_METHOD_CHK CHECK 
(PAYMENT_METHOD IN ('OnSite', 'BankTransfer', 'BLIK', 'CreditCard'))
ENABLE;

ALTER TABLE RESERVATIONS
ADD CONSTRAINT RESERVATIONS_PAY_STATUS_CHK CHECK 
(PAYMENT_STATUS IN ('UnPaid', 'Paid', 'Processing'))
ENABLE;

ALTER TABLE ROOMS
ADD CONSTRAINT ROOMS_STANDARD_CHK CHECK 
(ROOM_STANDARD IN ('Standard', 'Premium', 'SuperPremium'))
ENABLE;

ALTER TABLE USERS
ADD CONSTRAINT USERS_EMAIL_CHK CHECK 
(REGEXP_LIKE(Email, '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'))
ENABLE;

ALTER TABLE USERS
ADD CONSTRAINT USERS_GENDER_CHK CHECK 
(Gender IN ('F', 'M'))
ENABLE;